#!/bin/bash

# =============================================================================
# Group-Level Voxel-Wise SLURM Job Launcher
# =============================================================================
#
# This script launches SLURM jobs for group-level voxel-wise fMRI analysis.
# It automatically detects and launches scripts generated by create_group_voxelWise.sh
#
# Usage:
#   ./launch_group_voxelWise.sh                    # Launch all available scripts
#   ./launch_group_voxelWise.sh --data-source standard    # Launch only standard analysis
#   ./launch_group_voxelWise.sh --data-source placebo     # Launch only placebo analysis
#   ./launch_group_voxelWise.sh --analysis-type flameo    # Launch only flameo scripts
#   ./launch_group_voxelWise.sh --dry-run                 # Show what would be launched
#
# =============================================================================

# =============================================================================
# CONFIGURATION
# =============================================================================

# Base directory for data
BASE_DIR="/gscratch/scrubbed/fanglab/xiaoqian/NARSAD/work_flows"

# Data source configurations (matching create_group_voxelWise.sh)
DATA_SOURCE_DIRS=(
    "standard:groupLevel/whole_brain"
    "placebo:groupLevel/whole_brain/Placebo"
    "guess:groupLevel/whole_brain"
)

# Default settings
DATA_SOURCE=""
ANALYSIS_TYPE=""
DRY_RUN=false

# =============================================================================
# ARGUMENT PARSING
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --data-source)
            DATA_SOURCE="$2"
            shift 2
            ;;
        --analysis-type)
            ANALYSIS_TYPE="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "OPTIONS:"
            echo "  --data-source TYPE     Data source type: standard, placebo, or guess"
            echo "  --analysis-type TYPE   Analysis type: randomise, flameo"
            echo "  --dry-run              Show what would be launched without submitting"
            echo "  --help                 Show this help message"
            echo ""
            echo "EXAMPLES:"
            echo "  $0                                    # Launch all available scripts"
            echo "  $0 --data-source standard             # Launch only standard analysis"
            echo "  $0 --data-source placebo --analysis-type flameo"
            echo "  $0 --dry-run                          # Show what would be launched"
            exit 0
            ;;
        *)
            echo "Error: Unknown option: $1" >&2
            echo "Use --help for usage information" >&2
            exit 1
            ;;
    esac
done

# =============================================================================
# SCRIPT DISCOVERY AND LAUNCHING
# =============================================================================

echo "=========================================="
echo "Group-Level Voxel-Wise SLURM Job Launcher"
echo "=========================================="

if [[ -n "$DATA_SOURCE" ]]; then
    echo "Data source filter: $DATA_SOURCE"
fi

if [[ -n "$ANALYSIS_TYPE" ]]; then
    echo "Analysis type filter: $ANALYSIS_TYPE"
fi

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN MODE - No jobs will be submitted"
fi

echo "=========================================="

# Function to launch scripts from a specific directory
launch_scripts_from_dir() {
    local script_dir="$1"
    local data_source="$2"
    
    if [[ ! -d "$script_dir" ]]; then
        echo "Directory not found: $script_dir"
        return
    fi
    
    echo "Scanning directory: $script_dir"
    
    # Find all SLURM scripts in the directory
    local scripts_found=0
    local scripts_launched=0
    
    for script in "$script_dir"/*.sh; do
        # Check if file exists and is a regular file
        if [[ -f "$script" ]]; then
            # Apply filters if specified
            local should_launch=true
            
            # Filter by data source if specified
            if [[ -n "$DATA_SOURCE" && "$data_source" != "$DATA_SOURCE" ]]; then
                should_launch=false
            fi
            
            # Filter by analysis type if specified
            if [[ -n "$ANALYSIS_TYPE" && ! "$script" =~ ${ANALYSIS_TYPE} ]]; then
                should_launch=false
            fi
            
            if [[ "$should_launch" == true ]]; then
                scripts_found=$((scripts_found + 1))
                
                if [[ "$DRY_RUN" == true ]]; then
                    echo "  [DRY RUN] Would submit: $(basename "$script")"
                else
                    echo "  Submitting: $(basename "$script")"
                    sbatch "$script"
                    scripts_launched=$((scripts_launched + 1))
                fi
            fi
        fi
    done
    
    if [[ $scripts_found -eq 0 ]]; then
        echo "  No SLURM scripts found in: $script_dir"
    else
        if [[ "$DRY_RUN" == true ]]; then
            echo "  [DRY RUN] Found $scripts_found scripts (would launch $scripts_found)"
        else
            echo "  Found $scripts_found scripts, launched $scripts_launched"
        fi
    fi
    
    echo ""
}

# Launch scripts from all data source directories
for config in "${DATA_SOURCE_DIRS[@]}"; do
    IFS=':' read -r data_source script_subdir <<< "$config"
    script_dir="${BASE_DIR}/${script_subdir}"
    
    echo "Processing data source: $data_source"
    launch_scripts_from_dir "$script_dir" "$data_source"
done

echo "=========================================="
echo "Job launching completed!"
echo "=========================================="

if [[ "$DRY_RUN" == true ]]; then
    echo ""
    echo "To actually launch the jobs, run without --dry-run:"
    echo "  $0 ${DATA_SOURCE:+--data-source $DATA_SOURCE} ${ANALYSIS_TYPE:+--analysis-type $ANALYSIS_TYPE}"
fi


